#!/bin/sh
export GOPATH=/home/git/gopath
export PATH=$PATH:$GOPATH/bin
export DATABASE_URL=127.0.0.1:33333

rm -rf /home/git/gopath/src/gochat
mkdir /home/git/gopath/src/gochat

cd /home/git/gopath/src/gochat

git --work-tree=/home/git/gopath/src/gochat --git-dir=/home/git/gochat.git checkout -f

go install gochat/main

docker start mongodb

go test ./...

docker stop mongodb

#git init .git
go env
whoami
pwd
godep save ./...

#git config --global user.email "artem.chuzhmarov@gmail.com"
#git config --global user.name "Artem Chuzhmarov"

#git add .
#git commit -m "add dependencies"
#git remote add ocean dokku@46.101.198.165:gochat
#git push ocean master